define(function () {

    return {
        game_1_2_stripA: {
            ammount:[0,22],
            x:[570,60],
            y:[70,330],
            xOffset: [32,32],
            yOffset: [0,-0.5],
            parent: 'game1',
        },
        game_1_2_singleA: {
            ammount:[1,1],
            x:[1385,770],
            y:[78,329.5],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game1',
        },
        game_1_2_stripB: {
            ammount:[7,8],
            x:[1404,788],
            y:[101,360],
            xOffset: [-1,0.9],
            yOffset: [32,32],
            parent: 'game1',
        },
        game_1_2_singleB: {
            ammount:[1,1],
            x:[1379,785],
            y:[330,624],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game1',
        },
        game_1_2_stripC: {
            ammount:[25,22],
            x:[1344,745],
            y:[347,644],
            xOffset: [-32,-32],
            yOffset: [0,-0.2],
            parent: 'game1',
        },
        game_1_2_singleC: {
            ammount:[1,1],
            x:[546,30],
            y:[330,620],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game1',
        },
        game_1_2_stripD: {
            ammount:[7,1],
            x:[531,20],
            y:[300,494],
            xOffset: [-2,0],
            yOffset: [-32,0],
            parent: 'game1',
        },
        game_1_2_singleD: {
            ammount:[1,1],
            x:[538,26],
            y:[82,350],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game1',
        },
        game_3_4_stripA: {
            ammount:[0,22],
            x:[570,74],
            y:[370,660],
            xOffset: [32,32],
            yOffset: [0,0.5],
            parent: 'game2',
        },
        game_3_4_singleA: {
            ammount:[1,1],
            x:[1378,786],
            y:[380,690],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game2',
        },
        game_3_4_stripB: {
            ammount:[7,8],
            x:[1392,796],
            y:[414,730],
            xOffset: [2,0.2],
            yOffset: [36,32],
            parent: 'game2',
        },
        game_3_4_singleB: {
            ammount:[1,1],
            x:[1390,784],
            y:[670,990],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game2',
        },
        game_3_4_stripC: {
            ammount:[25,22],
            x:[1370,750],
            y:[690,1004],
            xOffset: [-32,-32],
            yOffset: [0,0.4],
            parent: 'game2',
        },
        game_3_4_singleC: {
            ammount:[1,1],
            x:[540,28],
            y:[674,996],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'game2',
        },
        game_3_4_stripD: {
            ammount:[7,2],
            x:[518,16],
            y:[634,852],
            xOffset: [2,0],
            yOffset: [-36,-32],
            parent: 'game2',
        },
        game_3_4_singleD: {
            ammount:[1,2],
            x:[546,14],
            y:[386,706],
            xOffset: [0,18],
            yOffset: [0,-32],
            parent: 'game2',
        },
        winUpto_StripA: {
            ammount:[4,4],
            x:[370,336],
            y:[147,145],
            xOffset: [32,32],
            yOffset: [6,6],
            parent: 'winUpTo',
        },
        winUpto_StripB: {
            ammount:[2,2],
            x:[480,436],
            y:[188,190],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'winUpTo',
        },
        winUpto_StripC: {
            ammount:[4,4],
            x:[465,424],
            y:[250,241],
            xOffset: [-32,-32],
            yOffset: [6,6],
            parent: 'winUpTo',
        },
        winUpto_StripD: {
            ammount:[3,2],
            x:[335,291],
            y:[262,252],
            xOffset: [-32,-32],
            yOffset: [-6,-6],
            parent: 'winUpTo',
        },
        winUpto_StripE: {
            ammount:[2,3],
            x:[270,234],
            y:[218,231],
            xOffset: [0,0],
            yOffset: [-32,-32],
            parent: 'winUpTo',
        },
        winUpto_StripF: {
            ammount:[2,2],
            x:[297,264],
            y:[162,159],
            xOffset: [36,32],
            yOffset: [-6,-6],
            parent: 'winUpTo',
        },
        cliffHangers_meter_stripA: {
            ammount:[14,10],
            x:[30,482],
            y:[380,224],
            xOffset: [32,32],
            yOffset: [-3.7,-2.3],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_singleA: {
            ammount:[1,1],
            x:[468,796],
            y:[342,208],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_stripB: {
            ammount:[3,2],
            x:[468,798],
            y:[374,234],
            xOffset: [-1.2,-1.4],
            yOffset: [32,32],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_singleB: {
            ammount:[1,1],
            x:[450,786],
            y:[456,296],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_stripC: {
            ammount:[13,10],
            x:[428,760],
            y:[460,298],
            xOffset: [-32,-32],
            yOffset: [1.8,0.4],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_singleC: {
            ammount:[1,1],
            x:[18,456],
            y:[474,280],
            xOffset: [0,0],
            yOffset: [0,0],
            parent: 'baseGameCHMeter',
        },
        cliffHangers_meter_stripD: {
            ammount:[2,1],
            x:[14,460],
            y:[438,250],
            xOffset: [1.2,2],
            yOffset: [-32,-32],
            parent: 'baseGameCHMeter',
        },
        showCaseShowDown_meter_stripA: {
            ammount:[13,9],
            x:[34,500],
            y:[520,104],
            xOffset: [32,32],
            yOffset: [-1.7,0.2],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_singleA: {
            ammount:[1,1],
            x:[448,788],
            y:[502,106],
            xOffset: [32,0],
            yOffset: [-1.4,0],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_stripB: {
            ammount:[3,2],
            x:[456,798],
            y:[532,132],
            xOffset: [-1.2,0],
            yOffset: [32,32],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_singleB: {
            ammount:[1,1],
            x:[444,786],
            y:[628,190],
            xOffset: [32,0],
            yOffset: [-1.4,0],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_stripC: {
            ammount:[13,10],
            x:[414,760],
            y:[632,190],
            xOffset: [-32,-32],
            yOffset: [-0.1,1],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_singleC: {
            ammount:[1,1],
            x:[16,466],
            y:[610,172],
            xOffset: [-32,0],
            yOffset: [0,0],
            parent: 'baseGameSSMeter',
        },
        showCaseShowDown_meter_stripD: {
            ammount:[2,2],
            x:[16,468],
            y:[580,142],
            xOffset: [0,0],
            yOffset: [-32,-32],
            parent: 'baseGameSSMeter',
        },
        cliffHangers_btn_stripA: {
            ammount:[8,5],
            x:[106,600],
            y:[100,883],
            xOffset: [32,32],
            yOffset: [0,0],
            parent: 'spinCliffHangersBtn',
        },
        cliffHangers_btn_stripB: {
            ammount:[7,4],
            x:[336,734],
            y:[125,904],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'spinCliffHangersBtn',
        },
        cliffHangers_btn_stripC: {
            ammount:[7,4],
            x:[310,710],
            y:[337,1024],
            xOffset: [-32,-32],
            yOffset: [0,0],
            parent: 'spinCliffHangersBtn',
        },
        cliffHangers_btn_stripD: {
            ammount:[7,4],
            x:[98,592],
            y:[315,1004],
            xOffset: [0,0],
            yOffset: [-32,-32],
            parent: 'spinCliffHangersBtn',
        },
        showCaseShowDownScene_stripA: {
            ammount:[26,14],
            x:[175,149],
            y:[155,356],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripB: {
            ammount:[0,5],
            x:[175,246],
            y:[515,356],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripC: {
            ammount:[26,7],
            x:[259,246],
            y:[205,576],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripD: {
            ammount:[0,14],
            x:[259,551],
            y:[515,356],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripE: {
            ammount:[6,0],
            x:[519,551],
            y:[205,766],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripF: {
            ammount:[12,14],
            x:[519,644],
            y:[445,356],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripG: {
            ammount:[5,0],
            x:[600,644],
            y:[195,766],
            xOffset: [0,0],
            yOffset: [32,32],
            parent: 'showdownScene',
        },
        showCaseShowDownScene_stripH: {
            ammount:[7,0],
            x:[600,0],
            y:[495,0],
            xOffset: [0,0],
            yOffset: [32,0],
            parent: 'showdownScene',
        },
    };
});