define({
    BetDown: ['Bet Down', 10],
    BetDown_1: ['Bet Down', 7],
    BetMax: ['Bet Max', 10],
    BetUp: ['Bet Up', 10],
    BetUp_1: ['Bet Up', 7],
    loseSFX: ['Better Luck Next Time audience', 0],
    wheelSpin: ['Big Wheel spinning', 0],
    winSFX: ['Congratulations audience', 0],
    climb: ['Mountaineer climbs_WoodThud1', 0],
    match: ['New_Win_V2', 5],
    click: ['GenericClick_1',5],
    click_1: ['GenericClick_1',8],
    cliffHangersActivated:['Cliff Hangers step activated',5],
    loseMusic: ['Better Luck Next Time', 1],
    cliffHangersMusic: ['Cliff Hangers music loop', 6],
    winMusic: ['Congratulations', 1],
    baseGameMusic: ['Music loop', 1],
    bigWinStartStop: ['Big Wheel starting-stopping', 2],
    climb2: ['Mountaineer climbs_WoodThud2', 2],
    wheelLand: ['Multiplier landed on - short', 2],
    play: ['Play Button_AcceptBet_3Seconds', 2],
    revealSymbol: ['Symbol reveal_V1', 2],
    revealSymbol_1: ['Symbol reveal_V1', 9],
    wheelAwarded: ['Big Wheel won', 3],
    climb3: ['Mountaineer climbs_WoodThud3', 3],
    mountainFall: ['Mountaineer falls off', 3],
    plaque: ['Plaque appears', 3],
    ding: ['Win Ding', 11],
});